# Generated by Django 2.2.1 on 2022-07-26 16:11

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220726_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
